import Link from "next/link";

type ExamplePost = {
  title: string;
  body: string[];
};

const examplePosts: ExamplePost[] = [
  {
    title: "Why consistency beats creativity for growth",
    body: [
      "Most people struggle with content because they treat it like inspiration.",
      "The real leverage comes from systems that compound over time.",
      "Here’s what most creators miss…",
    ],
  },
  {
    title: "The hidden cost of posting “when you feel like it”",
    body: [
      "Irregular posting doesn’t just hurt reach.",
      "It breaks trust with your audience.",
      "Consistency is a signal, not a tactic.",
    ],
  },
];

export default function HomePage() {
  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100">
      <div className="mx-auto w-full max-w-6xl px-6 py-10 lg:py-16">
        <Header />

        <div className="mt-10 grid gap-10 lg:mt-14 lg:grid-cols-2 lg:items-center">
          <Hero />
          <ExampleOutputCard posts={examplePosts} />
        </div>

        <FooterNote />
      </div>
    </main>
  );
}

function Header() {
  return (
    <header className="flex items-center justify-between">
      <div className="flex items-center gap-3">
        <div className="h-9 w-9 rounded-lg bg-neutral-900 ring-1 ring-neutral-800" />
        <div className="leading-tight">
          <div className="text-sm font-semibold tracking-tight">CRISP</div>
          <div className="text-xs text-neutral-400">Content Engine</div>
        </div>
      </div>

      <nav className="flex items-center gap-3">
        <Link
          href="/sign-in"
          className="rounded-full px-4 py-2 text-sm text-neutral-200 ring-1 ring-neutral-800 hover:bg-neutral-900"
        >
          Sign in
        </Link>
      </nav>
    </header>
  );
}

function Hero() {
  return (
    <section>
      <h1 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">
        Generate your next 9 posts in under 60 seconds
      </h1>

      <p className="mt-4 max-w-xl text-pretty text-base leading-relaxed text-neutral-300">
        CRISP turns how you think into a repeatable content system. No setup. No
        publishing required.
      </p>

      <div className="mt-7 flex flex-wrap items-center gap-3">
        <Link
          href="/preview"
          className="inline-flex items-center justify-center rounded-full bg-sky-400 px-5 py-2.5 text-sm font-semibold text-neutral-950 hover:bg-sky-300 focus:outline-none focus:ring-2 focus:ring-sky-300 focus:ring-offset-2 focus:ring-offset-neutral-950"
        >
          Try instant preview
        </Link>

        <Link
          href="/sign-in"
          className="inline-flex items-center justify-center rounded-full px-5 py-2.5 text-sm font-semibold text-neutral-100 ring-1 ring-neutral-800 hover:bg-neutral-900 focus:outline-none focus:ring-2 focus:ring-neutral-700 focus:ring-offset-2 focus:ring-offset-neutral-950"
        >
          Sign in
        </Link>
      </div>

      <ul className="mt-8 space-y-3 text-sm text-neutral-300">
        <li className="flex gap-3">
          <span className="mt-1 inline-block h-2 w-2 rounded-full bg-neutral-600" />
          Pick your niche, tone and goals
        </li>
        <li className="flex gap-3">
          <span className="mt-1 inline-block h-2 w-2 rounded-full bg-neutral-600" />
          See a structured content system, not random posts
        </li>
        <li className="flex gap-3">
          <span className="mt-1 inline-block h-2 w-2 rounded-full bg-neutral-600" />
          Save and publish when you are ready
        </li>
      </ul>
    </section>
  );
}

function ExampleOutputCard({ posts }: { posts: ExamplePost[] }) {
  return (
    <section className="rounded-2xl bg-neutral-950/40 p-5 ring-1 ring-neutral-800 backdrop-blur">
      <div className="flex items-center justify-between">
        <div>
          <div className="text-sm font-semibold text-neutral-100">
            Example output
          </div>
          <div className="mt-1 text-xs text-neutral-400">
            Preview generated by CRISP Content Engine
          </div>
        </div>

        <div className="hidden sm:flex items-center gap-2">
          <span className="rounded-full bg-neutral-900 px-3 py-1 text-xs text-neutral-300 ring-1 ring-neutral-800">
            LinkedIn
          </span>
          <span className="rounded-full bg-neutral-900 px-3 py-1 text-xs text-neutral-500 ring-1 ring-neutral-800">
            X
          </span>
          <span className="rounded-full bg-neutral-900 px-3 py-1 text-xs text-neutral-500 ring-1 ring-neutral-800">
            Instagram
          </span>
        </div>
      </div>

      <div className="mt-5 space-y-4">
        {posts.map((p, idx) => (
          <article
            key={idx}
            className="rounded-xl bg-neutral-950 p-4 ring-1 ring-neutral-800"
          >
            <div className="text-sm font-semibold text-neutral-100">
              {p.title}
            </div>

            <div className="mt-3 space-y-2 text-sm leading-relaxed text-neutral-300">
              {p.body.map((line, i) => (
                <p key={i} className="line-clamp-2">
                  {line}
                </p>
              ))}
            </div>

            <div className="mt-4 flex items-center justify-between">
              <span className="text-xs text-neutral-500">Truncated preview</span>
              <Link
                href="/preview"
                className="text-xs font-semibold text-sky-300 hover:text-sky-200"
              >
                Generate yours
              </Link>
            </div>
          </article>
        ))}
      </div>

      <div className="mt-5 rounded-xl bg-neutral-900/40 p-4 ring-1 ring-neutral-800">
        <div className="text-sm font-semibold text-neutral-100">
          Try the preview free
        </div>
        <div className="mt-1 text-sm text-neutral-300">
          Sign up only when you want to save or publish.
        </div>
      </div>
    </section>
  );
}

function FooterNote() {
  return (
    <div className="mt-10 border-t border-neutral-900 pt-6 text-xs text-neutral-500">
      By continuing you agree to the Terms and Privacy.{" "}
      <a href="/pricing" className="text-neutral-300 hover:text-neutral-200">
        View plans
      </a>
    </div>
  );
}
