'use client';

/**
 * StrategyDisplay
 *
 * Renders the master strategy JSON (from Make.com via Airtable field fldmz7OITQltKrgxQ)
 * in a fully human-readable, section-by-section UI.
 *
 * Handles both the Make.com nested format:
 *   brand_summary.one_liner, brand_understanding, pillars[], cadence, post_mix,
 *   voice, hashtag_buckets, image_direction, kpis, guardrails, automation_flags
 *
 * And the flat form-editor format:
 *   brand_name, audience, value_props, brand_goals, voice_rules, tone, etc.
 */

import { Edit } from 'lucide-react';

type StrategyDisplayProps = {
	strategyJson: any;
	brandName?: string;
	onEditClick?: () => void;
};

const get = (obj: any, ...keys: string[]): any => {
	if (!obj) return undefined;
	for (const k of keys) {
		const v = obj[k];
		if (v !== undefined && v !== null && v !== '') return v;
	}
	return undefined;
};

const toArr = (v: any): any[] => (Array.isArray(v) ? v : []);

function Section({ title, icon, children }: { title: string; icon: string; children: React.ReactNode }) {
	return (
		<section className="space-y-3">
			<h3 className="flex items-center gap-2 text-base font-semibold text-text border-b border-edge/60 pb-2">
				<span className="text-lg leading-none">{icon}</span>
				{title}
			</h3>
			{children}
		</section>
	);
}

function Field({ label, value }: { label: string; value: string }) {
	if (!value) return null;
	return (
		<div>
			<div className="text-xs font-medium text-text-dim uppercase tracking-wide mb-1">{label}</div>
			<p className="text-sm text-text leading-relaxed whitespace-pre-line">{value}</p>
		</div>
	);
}

function TagList({ items, color = 'primary' }: { items: string[]; color?: 'primary' | 'accent' | 'danger' | 'neutral' }) {
	if (!items.length) return null;
	const colors: Record<string, string> = {
		primary: 'border-primary/30 bg-primary/10 text-primary',
		accent: 'border-accent/30 bg-accent/10 text-accent',
		danger: 'border-danger/30 bg-danger/10 text-danger',
		neutral: 'border-edge/60 bg-surface/30 text-text-soft',
	};
	return (
		<div className="flex flex-wrap gap-1.5">
			{items.filter(Boolean).map((item, i) => (
				<span key={i} className={`inline-block text-xs px-2.5 py-1 rounded-full border ${colors[color]}`}>
					{item}
				</span>
			))}
		</div>
	);
}

function BulletList({ items, variant = 'neutral' }: { items: string[]; variant?: 'do' | 'dont' | 'neutral' }) {
	if (!items.length) return null;
	const dot: Record<string, string> = {
		do: 'text-accent',
		dont: 'text-danger',
		neutral: 'text-primary',
	};
	return (
		<ul className="space-y-1">
			{items.filter(Boolean).map((item, i) => (
				<li key={i} className="flex items-start gap-2 text-sm text-text">
					<span className={`mt-0.5 text-base leading-none ${dot[variant]}`}>
						{variant === 'do' ? '✓' : variant === 'dont' ? '✗' : '•'}
					</span>
					<span className="leading-relaxed">{item}</span>
				</li>
			))}
		</ul>
	);
}

function PercentBar({ label, pct }: { label: string; pct: number }) {
	return (
		<div className="space-y-1">
			<div className="flex justify-between text-xs text-text-soft">
				<span>{label}</span>
				<span className="font-medium text-text">{pct}%</span>
			</div>
			<div className="h-2 bg-edge/40 rounded-full overflow-hidden">
				<div className="h-full bg-primary/70 rounded-full" style={{ width: `${Math.min(pct, 100)}%` }} />
			</div>
		</div>
	);
}

export function StrategyDisplay({ strategyJson, brandName, onEditClick }: StrategyDisplayProps) {
	if (!strategyJson || (typeof strategyJson === 'object' && Object.keys(strategyJson).length === 0)) {
		return (
			<div className="card p-8 text-center text-text-dim">
				<p className="mb-1 font-medium">No strategy generated yet</p>
				<p className="text-sm">Your strategy will appear here once it has been generated by AI.</p>
			</div>
		);
	}

	const s = typeof strategyJson === 'string' ? (() => { try { return JSON.parse(strategyJson); } catch { return {}; } })() : strategyJson;

	// ── Make.com nested format ────────────────────────────────────────────
	const brandSummary = s.brand_summary || s.Brand_summary || {};
	const brandUnderstanding = s.brand_understanding || s.Brand_understanding || {};
	const pillars = toArr(s.pillars || s.Pillars || s.content_pillars);
	const cadence = s.cadence || s.Cadence || {};
	const platformCadence = toArr(s.platform_cadence);
	const postMix = s.post_mix || s.Post_mix || {};
	const voice = s.voice || s.Voice || {};
	const hashtagBuckets = s.hashtag_buckets || s.Hashtag_buckets || {};
	const imageDir = s.image_direction || s.Image_direction || {};
	const schedWindows = s.schedule_windows || s.Schedule_windows || {};
	const kpis = s.kpis || s.Kpis || {};
	const guardrails = s.guardrails || s.Guardrails || {};
	const autoFlags = s.automation_flags || s.Automation_flags || {};

	// ── Flat form-editor format (fallbacks) ───────────────────────────────
	const flatBrandName = s.brand_name || s.brand?.brand_name || brandName || '';
	const flatAudience = s.audience || s.brand?.audience || '';
	const flatValueProps = s.value_props || s.brand?.value_props || '';
	const flatBrandGoals = s.brand_goals || s.brand?.brand_goals || '';
	const flatOffers = s.offers || s.brand?.offers || '';
	const flatVoiceRules = s.voice_rules || s.voice?.voice_rules || '';
	const flatTone = s.tone || s.voice?.tone || '';
	const flatPersonality = toArr(s.personality || s.voice?.personality);

	// Brand summary fields
	const oneLiner = get(brandSummary, 'one_liner', 'One liner') || flatBrandName;
	const positioning = get(brandSummary, 'positioning', 'Positioning') || flatValueProps;

	// Brand understanding fields
	const buSummary = get(brandUnderstanding, 'summary', 'Summary');
	const perceivedAudience = get(brandUnderstanding, 'perceived_audience', 'Perceived audience') || flatAudience;
	const toneDesc = get(brandUnderstanding, 'tone_description', 'Tone description') || flatTone;
	const visualImpression = get(brandUnderstanding, 'visual_impression', 'Visual impression');

	// Content mix
	const tlPct = get(postMix, 'thought_leadership_pct', 'Thought leadership pct');
	const eduPct = get(postMix, 'educational_pct', 'Educational pct');
	const promoPct = get(postMix, 'promo_pct', 'Promo pct');
	const commPct = get(postMix, 'community_pct', 'Community pct');

	// Voice dos/donts
	const voiceSummary = get(voice, 'summary', 'Summary') || flatVoiceRules;
	const dos = toArr(voice.dos || voice.Dos).filter(Boolean);
	const donts = toArr(voice.donts || voice.Donts).filter(Boolean);

	// Guardrails
	const avoidTopics = toArr(guardrails.avoid_topics || guardrails.Avoid_topics || s.topics_to_avoid).filter(Boolean);
	const includeKw = toArr(guardrails.include_keywords || guardrails.Include_keywords || s.brand_keywords).filter(Boolean);
	const excludeKw = toArr(guardrails.exclude_keywords || guardrails.Exclude_keywords || s.exclude_keywords).filter(Boolean);

	// KPIs
	const kpiPrimary = get(kpis, 'primary', 'Primary');
	const kpiSecondary = get(kpis, 'secondary', 'Secondary');
	const kpiAlign = get(kpis, 'objective_alignment', 'objective_alignment');

	// Image direction
	const imgStyle = get(imageDir, 'style_notes', 'Style notes');
	const imgSource = get(imageDir, 'source_preference', 'Source preference');

	// Cadence: normalise both formats
	const cadenceEntries: Array<{ platform: string; frequency: string }> = [];
	if (Object.keys(cadence).length > 0) {
		Object.entries(cadence).forEach(([platform, freq]) => {
			if (freq && String(freq).trim()) cadenceEntries.push({ platform, frequency: String(freq) });
		});
	}
	if (platformCadence.length > 0) {
		platformCadence.forEach((c: any) => {
			if (c.platform) cadenceEntries.push({ platform: c.platform, frequency: c.postsPerWeek ? `${c.postsPerWeek} posts/week` : '' });
		});
	}

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex items-center justify-between">
				<div>
					{oneLiner && <p className="text-lg font-semibold text-text">{oneLiner}</p>}
					{positioning && oneLiner !== positioning && (
						<p className="text-sm text-text-soft mt-1 leading-relaxed max-w-2xl">{positioning}</p>
					)}
				</div>
				{onEditClick && (
					<button
						onClick={onEditClick}
						className="shrink-0 px-3 py-1.5 rounded-xl2 border border-edge/60 bg-surface/30 hover:bg-surface/50 flex items-center gap-2 text-sm text-text-soft"
					>
						<Edit className="w-3.5 h-3.5" />
						Edit
					</button>
				)}
			</div>

			{/* Brand Understanding */}
			{(buSummary || perceivedAudience || toneDesc || visualImpression || flatAudience || flatBrandGoals) && (
				<Section title="Brand Understanding" icon="🧭">
					<div className="grid gap-3">
						{buSummary && <Field label="Overview" value={buSummary} />}
						{perceivedAudience && <Field label="Target Audience" value={perceivedAudience} />}
						{flatBrandGoals && !buSummary && <Field label="Brand Goals" value={flatBrandGoals} />}
						{toneDesc && <Field label="Tone" value={toneDesc} />}
						{visualImpression && <Field label="Visual Impression" value={visualImpression} />}
						{flatOffers && <Field label="Offers & Products" value={flatOffers} />}
					</div>
				</Section>
			)}

			{/* Content Pillars */}
			{pillars.length > 0 && (
				<Section title="Content Pillars" icon="🏛️">
					<div className="grid gap-3 sm:grid-cols-2">
						{pillars.map((pillar: any, i: number) => {
							const name = get(pillar, 'name', 'Name', 'title') || `Pillar ${i + 1}`;
							const why = get(pillar, 'why', 'description', 'Why');
							const formats = toArr(pillar.content_formats).filter(Boolean);
							const hooks = toArr(pillar.example_hooks).filter(Boolean);
							const topics = toArr(pillar.topics).filter(Boolean);
							return (
								<div key={pillar.id || i} className="p-4 rounded-xl2 border border-edge/60 bg-surface/20 space-y-2">
									<div className="flex items-start gap-2">
										<span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/20 text-primary text-xs font-semibold flex items-center justify-center mt-0.5">
											{i + 1}
										</span>
										<p className="font-semibold text-text">{name}</p>
									</div>
									{why && <p className="text-sm text-text-soft leading-relaxed pl-8">{why}</p>}
									{(formats.length > 0 || topics.length > 0) && (
										<div className="pl-8">
											<TagList items={formats.length > 0 ? formats : topics} color="neutral" />
										</div>
									)}
									{hooks.length > 0 && (
										<div className="pl-8 pt-1">
											<p className="text-xs text-text-dim mb-1 font-medium">Example hooks</p>
											<ul className="space-y-0.5">
												{hooks.map((h: string, j: number) => (
													<li key={j} className="text-xs text-text-soft leading-relaxed">• {h}</li>
												))}
											</ul>
										</div>
									)}
								</div>
							);
						})}
					</div>
				</Section>
			)}

			{/* Posting Cadence */}
			{cadenceEntries.length > 0 && (
				<Section title="Posting Schedule" icon="📅">
					<div className="grid gap-2 sm:grid-cols-2">
						{cadenceEntries.map(({ platform, frequency }, i) => (
							<div key={i} className="flex items-center justify-between p-3 rounded-xl2 border border-edge/60 bg-surface/20">
								<span className="text-sm font-medium text-text capitalize">{platform}</span>
								{frequency && <span className="text-sm text-text-soft">{frequency}</span>}
							</div>
						))}
					</div>
				</Section>
			)}

			{/* Content Mix */}
			{(tlPct !== undefined || eduPct !== undefined || promoPct !== undefined || commPct !== undefined) && (
				<Section title="Content Mix" icon="📊">
					<div className="space-y-3 max-w-md">
						{tlPct !== undefined && <PercentBar label="Thought Leadership" pct={Number(tlPct)} />}
						{eduPct !== undefined && <PercentBar label="Educational" pct={Number(eduPct)} />}
						{promoPct !== undefined && <PercentBar label="Promotional" pct={Number(promoPct)} />}
						{commPct !== undefined && <PercentBar label="Community" pct={Number(commPct)} />}
					</div>
				</Section>
			)}

			{/* Voice & Tone */}
			{(voiceSummary || dos.length > 0 || donts.length > 0 || flatPersonality.length > 0) && (
				<Section title="Voice & Tone" icon="🎙️">
					<div className="space-y-4">
						{voiceSummary && <Field label="Voice" value={voiceSummary} />}
						{flatPersonality.length > 0 && (
							<div>
								<div className="text-xs font-medium text-text-dim uppercase tracking-wide mb-2">Personality Traits</div>
								<TagList items={flatPersonality} color="primary" />
							</div>
						)}
						{(dos.length > 0 || donts.length > 0) && (
							<div className="grid gap-4 sm:grid-cols-2">
								{dos.length > 0 && (
									<div>
										<div className="text-xs font-medium text-accent uppercase tracking-wide mb-2">Do</div>
										<BulletList items={dos} variant="do" />
									</div>
								)}
								{donts.length > 0 && (
									<div>
										<div className="text-xs font-medium text-danger uppercase tracking-wide mb-2">Don't</div>
										<BulletList items={donts} variant="dont" />
									</div>
								)}
							</div>
						)}
					</div>
				</Section>
			)}

			{/* Hashtag Buckets */}
			{typeof hashtagBuckets === 'object' && Object.keys(hashtagBuckets).length > 0 && (
				<Section title="Hashtag Strategy" icon="#️⃣">
					<div className="space-y-3">
						{Object.entries(hashtagBuckets).map(([platform, tags]) => {
							const list = Array.isArray(tags) ? tags : typeof tags === 'string' ? [tags] : [];
							if (!list.length) return null;
							return (
								<div key={platform}>
									<div className="text-xs font-medium text-text-dim mb-1.5 capitalize">{platform}</div>
									<TagList items={list} color="neutral" />
								</div>
							);
						})}
					</div>
				</Section>
			)}

			{/* Image Direction */}
			{(imgStyle || imgSource) && (
				<Section title="Image Direction" icon="🖼️">
					<div className="grid gap-3">
						{imgStyle && <Field label="Style" value={imgStyle} />}
						{imgSource && <Field label="Source Preference" value={imgSource} />}
					</div>
				</Section>
			)}

			{/* Schedule Windows */}
			{get(schedWindows, 'notes', 'Notes') && (
				<Section title="Schedule Windows" icon="⏰">
					<Field label="Notes" value={get(schedWindows, 'notes', 'Notes')} />
				</Section>
			)}

			{/* KPIs */}
			{(kpiPrimary || kpiSecondary || kpiAlign) && (
				<Section title="Key Performance Indicators" icon="🎯">
					<div className="grid gap-3">
						{kpiPrimary && <Field label="Primary KPI" value={kpiPrimary} />}
						{kpiSecondary && <Field label="Secondary KPI" value={kpiSecondary} />}
						{kpiAlign && <Field label="Objective Alignment" value={kpiAlign} />}
					</div>
				</Section>
			)}

			{/* Guardrails */}
			{(avoidTopics.length > 0 || includeKw.length > 0 || excludeKw.length > 0 || get(guardrails, 'content_rules') || s.content_rules || get(guardrails, 'risk_tolerance') || s.risk_tolerance) && (
				<Section title="Guardrails" icon="🛡️">
					<div className="space-y-3">
						{avoidTopics.length > 0 && (
							<div>
								<div className="text-xs font-medium text-text-dim uppercase tracking-wide mb-2">Topics to Avoid</div>
								<TagList items={avoidTopics} color="danger" />
							</div>
						)}
						{includeKw.length > 0 && (
							<div>
								<div className="text-xs font-medium text-text-dim uppercase tracking-wide mb-2">Include Keywords</div>
								<TagList items={includeKw} color="accent" />
							</div>
						)}
						{excludeKw.length > 0 && (
							<div>
								<div className="text-xs font-medium text-text-dim uppercase tracking-wide mb-2">Exclude Keywords</div>
								<TagList items={excludeKw} color="danger" />
							</div>
						)}
						{(get(guardrails, 'content_rules') || s.content_rules) && (
							<Field label="Content Rules" value={get(guardrails, 'content_rules') || s.content_rules} />
						)}
						{(get(guardrails, 'risk_tolerance') || s.risk_tolerance) && (
							<Field label="Risk Tolerance" value={get(guardrails, 'risk_tolerance') || s.risk_tolerance} />
						)}
					</div>
				</Section>
			)}

			{/* Automation */}
			{Object.keys(autoFlags).length > 0 && (
				<Section title="Automation Settings" icon="⚙️">
					<div className="grid gap-2 sm:grid-cols-2">
						{autoFlags.seasonal_allowed !== undefined && (
							<div className="p-3 rounded-xl2 border border-edge/60 bg-surface/20 flex items-center justify-between">
								<span className="text-sm text-text-soft">Seasonal content</span>
								<span className={`text-sm font-medium ${autoFlags.seasonal_allowed ? 'text-accent' : 'text-text-dim'}`}>
									{autoFlags.seasonal_allowed ? 'Enabled' : 'Disabled'}
								</span>
							</div>
						)}
						{get(autoFlags, 'variations_per_concept', 'Variations per concept') && (
							<div className="p-3 rounded-xl2 border border-edge/60 bg-surface/20 flex items-center justify-between">
								<span className="text-sm text-text-soft">Variations per concept</span>
								<span className="text-sm font-medium text-text">{get(autoFlags, 'variations_per_concept', 'Variations per concept')}</span>
							</div>
						)}
						{autoFlags.video_enabled !== undefined && (
							<div className="p-3 rounded-xl2 border border-edge/60 bg-surface/20 flex items-center justify-between">
								<span className="text-sm text-text-soft">Video content</span>
								<span className={`text-sm font-medium ${autoFlags.video_enabled ? 'text-accent' : 'text-text-dim'}`}>
									{autoFlags.video_enabled ? 'Enabled' : 'Disabled'}
								</span>
							</div>
						)}
					</div>
				</Section>
			)}
		</div>
	);
}
